modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "random_crafts"
modUrl = "https://modrinth.com/mod/random-crafts"
version = "${mod_version}"
displayName = "Random Crafts"
authors = "Weyne1"
description = '''
Let's randomize crafts for each world! Let the chaos begin...
'''
logoFile = "icon.png"

[[dependencies.random_crafts]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_crafts]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_crafts]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
