architectury {
    //noinspection GroovyAssignabilityCheck
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
}

processResources {
    inputs.property 'datapack_name', rootProject.datapack_name
    inputs.property 'datapack_description', rootProject.datapack_description
    inputs.property 'mc_min_pack_format', rootProject.mc_min_pack_format
    inputs.property 'mc_max_pack_format', rootProject.mc_max_pack_format

    filesMatching('randomcrafts-datapack.properties') {
        expand(
                datapack_name: rootProject.datapack_name,
                datapack_description: rootProject.datapack_description,
                mc_min_pack_format: rootProject.mc_min_pack_format,
                mc_max_pack_format: rootProject.mc_min_pack_format
        )
    }
}
